name: friendlychat
description: Android,iOS,Web Flutter application.
# version: 1.0.0
#homepage: https://www.example.com

version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter_web: any
  flutter_web_ui: any
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  build_runner: ^1.6.0
  build_web_compilers: ^2.3.0
  build_test: ^0.10.2
  pedantic: ^1.8.0
  flutter_test:
    sdk: flutter

dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui

flutter:
  uses-material-design: true

module:
  androidX: true